FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /app

# Copy csproj and restore as distinct layers
COPY ["server/SuperheroApp.API/SuperheroApp.API.csproj", "SuperheroApp.API/"]
COPY ["server/SuperheroApp.Core/SuperheroApp.Core.csproj", "SuperheroApp.Core/"]
COPY ["server/SuperheroApp.Infrastructure/SuperheroApp.Infrastructure.csproj", "SuperheroApp.Infrastructure/"]
RUN dotnet restore "SuperheroApp.API/SuperheroApp.API.csproj"

# Copy everything else and build
COPY ./server /app
WORKDIR "/app/SuperheroApp.API"

RUN dotnet restore

FROM build AS publish
CMD ["dotnet", "watch", "run", "--project" , "SuperheroApp.API.csproj",  "--urls", "https://*:80;http://*:5000"]